'use client';
import {useState} from 'react';
import {sampleResume,sampleJob,sampleClaims,matchPreview,claimRows,money,downloadText} from '@/lib/demo';
export function DemoLab(){
 const [resume,setResume]=useState(sampleResume),[job,setJob]=useState(sampleJob),[match,setMatch]=useState<ReturnType<typeof matchPreview>|null>(null),[matchError,setMatchError]=useState('');
 const [claims,setClaims]=useState(sampleClaims),[rows,setRows]=useState<ReturnType<typeof claimRows>>([]),[claimError,setClaimError]=useState('');
 const [role,setRole]=useState('Junior automation developer'),[evidence,setEvidence]=useState('Built a Python API and documented the setup.'),[tone,setTone]=useState('Professional'),[draft,setDraft]=useState('');
 return <div className="lab-stack">
  <section className="lab-card" id="job-match"><div className="lab-heading"><span className="eyebrow">01 / JOB MATCH</span><span className="repo-state">Browser preview · keyword rules</span></div><h2>See the evidence behind a match.</h2><p>A simplified portfolio preview, separate from the Python agent. It checks 11 fixed skill phrases using word boundaries. No AI request is made, and the percentage is phrase coverage—not suitability for a job. Inputs stay in this page.</p>
   <form onSubmit={e=>{e.preventDefault();try{setMatch(matchPreview(resume,job));setMatchError('')}catch(e){setMatch(null);setMatchError((e as Error).message)}}}><div className="lab-columns"><label>Résumé text<textarea maxLength={10000} required value={resume} onChange={e=>{setResume(e.target.value);setMatch(null)}}/></label><label>Job description<textarea maxLength={10000} required value={job} onChange={e=>{setJob(e.target.value);setMatch(null)}}/></label></div><div className="lab-actions"><button className="button primary">Compare sample</button><button type="button" className="button secondary" onClick={()=>{setResume(sampleResume);setJob(sampleJob);setMatch(null);setMatchError('')}}>Reset sample</button><a href="https://github.com/Santo250499/job-match-agent#run-locally" target="_blank" rel="noreferrer">Run the full agent ↗</a></div></form>
   {matchError&&<p role="alert">{matchError}</p>}{match&&<div className="lab-result" aria-live="polite"><h3>{match.coverage===null?'No recognised skill phrases':`${match.coverage}% phrase coverage`}</h3><p>{match.matched.length} of {match.required.length} recognised job phrases also appear in the résumé.</p><div className="lab-columns"><div><h4>Found in both</h4><p>{match.matched.join(' · ')||'None'}</p></div><div><h4>Not found in résumé</h4><p>{match.missing.join(' · ')||'None'}</p></div></div><p className="small-note">This cannot understand negation, proficiency, context or synonyms. Check every match against the original evidence.</p></div>}
  </section>
  <section className="lab-card" id="claims"><div className="lab-heading"><span className="eyebrow">02 / CLAIM AMOUNTS</span><span className="repo-state">Browser preview · text only</span></div><h2>From status rows to reviewable totals.</h2><p>Try a simplified version of the repository’s documented text rules. Use one row per line and positive $ amounts. Review the classifications before exporting; spreadsheet and screenshot processing are available in the full Python application.</p><form onSubmit={e=>{e.preventDefault();try{setRows(claimRows(claims));setClaimError('')}catch(e){setRows([]);setClaimError((e as Error).message)}}}><label>Claim status rows<textarea maxLength={20000} value={claims} required onChange={e=>{setClaims(e.target.value);setRows([])}}/></label><div className="lab-actions"><button className="button primary">Calculate totals</button><button type="button" className="button secondary" onClick={()=>{setClaims(sampleClaims);setRows([]);setClaimError('')}}>Reset sample</button><a href="https://github.com/Santo250499/ai-claim-amount-calculator#how-to-run" target="_blank" rel="noreferrer">Run the full calculator ↗</a></div></form>{claimError&&<p role="alert">{claimError}</p>}{rows.length>0&&<div className="lab-result" aria-live="polite"><div className="lab-columns"><div><span>Pending</span><h3>{money(rows.reduce((a,r)=>a+r.pending,0))}</h3></div><div><span>Paid</span><h3>{money(rows.reduce((a,r)=>a+r.paid,0))}</h3></div><div><span>Net open · pending − paid</span><h3>{money(rows.reduce((a,r)=>a+r.pending-r.paid,0))}</h3></div></div><div className="table-scroll" tabIndex={0} aria-label="Claim classification results"><table><thead><tr><th>Row</th><th>Classification</th><th>Pending</th><th>Paid</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.category}</td><td>{money(r.pending)}</td><td>{money(r.paid)}</td></tr>)}</tbody></table></div><button className="button secondary" onClick={()=>downloadText('claim-preview.csv','Row,Classification,Pending AUD,Paid AUD\n'+rows.map(r=>[r.id,r.category,(r.pending/100).toFixed(2),(r.paid/100).toFixed(2)].join(',')).join('\n'),'text/csv')}>Download reviewed totals CSV</button><p className="small-note">Edit the source rows and recalculate to correct a classification. This preview reads the first amount on a line; unsupported and negative amounts need manual review.</p></div>}</section>
  <section className="lab-card" id="application"><div className="lab-heading"><span className="eyebrow">03 / APPLICATION ASSISTANT</span><span className="repo-state">Template preview · no AI generation</span></div><h2>Keep the application grounded in facts.</h2><p>Explore a small part of the application workflow with a fixed outreach template. The full Streamlit app uses OpenAI for analysis, cover letters, CV rewrites and interview preparation.</p><form onSubmit={e=>{e.preventDefault();setDraft(`${tone==='Friendly'?'Hello':'Dear hiring team'},\n\nI’m interested in the ${role.trim()} opportunity. Here is one example of my relevant work:\n\n${evidence.trim()}\n\nI would welcome a conversation about the role and how this experience could contribute to your team.\n\nKind regards,\n[Your name]`)}}><div className="lab-columns"><label>Target role<input required maxLength={100} value={role} onChange={e=>{setRole(e.target.value);setDraft('')}}/></label><label>Tone<select value={tone} onChange={e=>{setTone(e.target.value);setDraft('')}}><option>Professional</option><option>Friendly</option></select></label></div><label>One truthful example<textarea required maxLength={1200} value={evidence} onChange={e=>{setEvidence(e.target.value);setDraft('')}}/></label><div className="lab-actions"><button className="button primary">Create template preview</button><a href="https://github.com/Santo250499/ai-job-application-assistant#setup-and-run" target="_blank" rel="noreferrer">Run the full assistant ↗</a></div></form>{draft&&<div className="lab-result" aria-live="polite"><h3>Your draft</h3><pre>{draft}</pre><button className="button secondary" onClick={()=>downloadText('application-template.txt',draft)}>Download draft</button><p className="small-note">Review the example and replace the name before sending. This template has not verified your claims.</p></div>}</section>
 </div>
}

