'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import snapshot from '@/content/evidence-snapshot.json';
import {dateLabel,safeUrl,editorial} from '@/content/github';
type Run={name:string;status:string;conclusion:string|null;html_url:string;updated_at:string;head_sha:string};
type Release={tag_name:string;html_url:string;published_at:string};
type Milestone={title:string;state:string;open_issues:number;closed_issues:number;html_url:string};
type Evidence={repo:string;run:Run|null;release:Release|null;milestones:Milestone[]|null};
const base='https://api.github.com/repos/Santo250499/';
export function EngineeringEvidence(){
 const [data,setData]=useState<Evidence[]>(snapshot.projects),[checked,setChecked]=useState(snapshot.checkedAt),[notice,setNotice]=useState('Saved GitHub evidence'),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{const controller=new AbortController();let active=true;const timer=setTimeout(()=>controller.abort(),15000);setLoading(true);
 async function get(path:string){const res=await fetch(base+path,{signal:controller.signal,headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw Error('GitHub unavailable');return res.json()}
 Promise.all(snapshot.projects.map(async p=>{const [release,runs,milestones]=await Promise.all([get(p.repo+'/releases?per_page=1'),get(p.repo+'/actions/runs?per_page=1&branch=main'),get(p.repo+'/milestones?state=all&per_page=100')]);if(!Array.isArray(release)||!Array.isArray(runs.workflow_runs)||!Array.isArray(milestones))throw Error('Invalid response');return {repo:p.repo,release:release[0]||null,run:runs.workflow_runs[0]||null,milestones} as Evidence})).then(result=>{if(active){setData(result);setChecked(new Date().toISOString());setNotice('Live GitHub evidence')}}).catch(()=>{if(active)setNotice('Live evidence unavailable or rate-limited. Showing the last successful snapshot.')}).finally(()=>{clearTimeout(timer);if(active)setLoading(false)});return()=>{active=false;controller.abort();clearTimeout(timer)}},[attempt]);
 return <section className="lab-section" id="engineering"><div className="library-heading"><div><span className="eyebrow">ENGINEERING / PROGRESS</span><h2>Evidence you can inspect.</h2><p>Releases, the latest main-branch workflow and up to 100 milestones per featured project.</p></div><button className="button secondary" disabled={loading} onClick={()=>setAttempt(x=>x+1)}>{loading?'Checking evidence…':'Refresh evidence'}</button></div><p className="small-note" role="status">{notice} · checked {dateLabel(checked)}.</p><div className="evidence-grid">{data.map(p=><article className="lab-card" key={p.repo}><span className="status-label">{p.release?'RELEASE PUBLISHED':'SOURCE AVAILABLE'}</span><h3>{editorial[p.repo]?.title||p.repo}</h3><ul className="evidence-list"><li><small>Latest published release</small>{p.release?<a href={safeUrl(p.release.html_url)||`https://github.com/Santo250499/${p.repo}/releases`} target="_blank" rel="noreferrer">{p.release.tag_name}</a>:<span>No published release returned</span>}</li><li><small>Latest main-branch workflow</small>{p.run?<><a href={safeUrl(p.run.html_url)||`https://github.com/Santo250499/${p.repo}/actions`} target="_blank" rel="noreferrer">{p.run.name}: {p.run.conclusion||p.run.status} ↗</a><small>{dateLabel(p.run.updated_at)} · {p.run.head_sha.slice(0,7)}</small></>:<span>No public workflow run returned</span>}</li><li><small>GitHub milestones</small>{p.milestones?.length?p.milestones.map(m=><div key={m.html_url}><a href={safeUrl(m.html_url)||`https://github.com/Santo250499/${p.repo}/milestones`} target="_blank" rel="noreferrer">{m.title}</a><small> · {m.state} · {m.closed_issues} closed / {m.open_issues+m.closed_issues} issues</small></div>):<span>No milestones published yet</span>}</li></ul><div className="lab-actions"><a href={`https://github.com/Santo250499/${p.repo}/milestones`} target="_blank" rel="noreferrer">Milestones ↗</a><a href={`https://github.com/Santo250499/${p.repo}/issues`} target="_blank" rel="noreferrer">Issues ↗</a></div><p className="small-note">A workflow result describes that run; it does not measure AI accuracy.</p></article>)}</div><div className="lab-card lab-section"><span className="eyebrow">NEXT STEPS / DOCUMENTED DIRECTION</span><h3>Job Match Agent roadmap</h3><p>Potential improvements listed in the repository: PDF/DOCX parsing, evaluation datasets, authentication, analysis history and cloud deployment. These are roadmap ideas; no delivery dates or in-progress milestones are claimed.</p><a className="text-link" href="https://github.com/Santo250499/job-match-agent#roadmap" target="_blank" rel="noreferrer">Read the source roadmap ↗</a></div><Link className="button primary" href="/demos/">Try project previews</Link> <Link className="button secondary" href="/evaluation/">Evaluation & limitations</Link></section>
}
