import Link from 'next/link';
import {Code2,BriefcaseBusiness} from 'lucide-react';
import {Eyebrow,Workbench,SectionHeading} from '@/components/ui';
import {ProjectCard} from '@/components/projects';
import {CurrentlyBuilding,SkillsGrid,ExperienceCard,WebSeo,ContactCTA} from '@/components/sections';
import {projects} from '@/content/projects';
import {profile} from '@/content/profile';
import {DepthStage} from '@/components/depth-stage';
import {ProfileIntro} from '@/components/profile-intro';
import {FeaturedRepositories} from '@/components/featured-repositories';
import {pageMeta,schema} from '@/content/metadata';
export const metadata=pageMeta(profile.title,'Md Tanvir Mannan, Gold Coast: ICT support and systems experience across Microsoft 365, Intune and Entra ID, plus AI and automation tools built with Python, FastAPI and PowerShell.','/');
export default function Home(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:schema({'@context':'https://schema.org','@type':'WebSite',name:`${profile.name} | ${profile.title}`,url:profile.siteUrl||undefined,description:'Enterprise IT support and systems experience, plus practical AI and automation projects.'})}}/><section className="hero container"><div className="hero-copy"><Eyebrow>MD TANVIR MANNAN / GOLD COAST</Eyebrow><h1>Reliable IT.<br/><span>Practical</span><br/>automation.</h1><p>I’m an ICT Support Officer on the Gold Coast, supporting Microsoft 365, Intune and Entra ID across a multi-site organisation, and building AI and automation tools with Python, FastAPI and PowerShell.</p><div className="hero-actions"><Link href="/projects/" className="button primary"><Code2 size={18}/> Explore all projects</Link><Link href="/github/" className="button secondary">Work dashboard</Link><Link href="/demos/" className="button secondary">Try the demos</Link><Link href="/resume/" className="text-link">Résumé & download</Link><a className="text-link" href="/Md-Tanvir-Mannan-Resume.pdf" download>Download CV · PDF</a></div><div className="hero-note"><span>ICT Support &amp; Systems Professional</span><span>Building AI and Automation Tools</span><span>Gold Coast</span></div></div><DepthStage><Workbench/></DepthStage></section><ProfileIntro/><section className="proof-band"><div className="container proof-grid"><div className="proof-label"><BriefcaseBusiness size={20}/><span>BUILT ON REAL-WORLD<br/>ENTERPRISE EXPERIENCE</span></div><div><strong>2,200<span>+</span></strong><p>users in the supported environment</p></div><div><strong>20<span>+</span></strong><p>sites across the organisation</p></div><div><strong>500<span>+</span></strong><p>Windows devices deployed with Autopilot & Intune</p></div></div></section><FeaturedRepositories/><section className="container"><CurrentlyBuilding/></section><section className="container section"><SectionHeading kicker="02 / THE TOOLKIT" title="From idea to working solution." description="Enterprise IT and systems skills from my day job, plus a growing AI and software toolkit." href="/skills/" label="Explore all skills"/><SkillsGrid compact/></section><section className="container"><SectionHeading kicker="03 / THE FOUNDATION" title="Real systems. Real responsibility."/><ExperienceCard/></section><section className="container section"><SectionHeading kicker="04 / CONNECTED CAPABILITIES" title="Useful, usable and discoverable."/><WebSeo/></section><section className="container credentials-strip"><div><Eyebrow>CONTINUOUS DEVELOPMENT</Eyebrow><h3>Skills are a practice, not a percentage.</h3><p>CCNA (2023) and CEH (2024), alongside hands-on projects and ongoing professional development.</p></div><Link href="/certifications/" className="text-link">Certifications & learning</Link></section><div className="container section"><ContactCTA/></div></>}
