'use client';
import Link from 'next/link';
import {useState} from 'react';
import {BrainCircuit,Code2,Network,Terminal,SlidersHorizontal} from 'lucide-react';
import {categories,projects,type Project} from '@/content/projects';
import {Tags} from './ui';
export function ProjectVisual({project}:{project:Project}){const Icon=project.kind==='ai'?BrainCircuit:project.kind==='web'?Code2:Network;return <div className={'project-visual '+project.kind}><div className="visual-top"><span>{project.kind==='ai'?'INTELLIGENT APPLICATION':project.kind==='web'?'WEB DEVELOPMENT':'ENTERPRISE TECHNOLOGY'}</span><span>/{String(projects.indexOf(project)+1).padStart(2,'0')}</span></div><Icon size={45} strokeWidth={1}/><div className="visual-bottom"><code>{project.kind==='ai'?'input → analyse → recommend':project.kind==='web'?'design → build → deploy':'configure → support → improve'}</code><span>CONCEPT</span></div></div>}
export function ProjectCard({project}:{project:Project}){return <article className="project-card"><Link href={'/projects/'+project.slug+'/'} tabIndex={-1} aria-hidden="true"><ProjectVisual project={project}/></Link><div className="project-card-body"><span className="status-label">{project.status}</span><h3><Link href={'/projects/'+project.slug+'/'}>{project.title}</Link></h3><p>{project.summary}</p><Tags items={project.technologies}/>{project.website&&<a className="card-link" href={project.website} target="_blank" rel="noreferrer">Live site <span aria-hidden="true">↗</span></a>}<Link href={'/projects/'+project.slug+'/'} className="card-link">Read case study <span aria-hidden="true">+</span></Link></div></article>}
export function ProjectCollection(){const [category,setCategory]=useState('All');const visible=projects.filter(p=>category==='All'||p.categories.includes(category));return <><div className="filter-label"><SlidersHorizontal size={15}/> EXPLORE BY FOCUS</div><div className="filters" aria-label="Project categories">{categories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="result-count" aria-live="polite">{visible.length} {visible.length===1?'project':'projects'}{category!=='All'?' · '+category:''}</p>{visible.length?<div className="project-grid">{visible.map(p=><ProjectCard key={p.slug} project={p}/>)}</div>:<div className="empty-state"><Terminal size={28}/><h3>A space for what comes next.</h3><p>No published {category.toLowerCase()} case study yet. New work will appear here as projects are documented.</p><button className="button secondary" onClick={()=>setCategory('All')}>View all projects</button></div>}</>}
