import Link from 'next/link';
import {Code2,GitBranch,Workflow,BrainCircuit,Layers,Search,Network} from 'lucide-react';
import {SectionHeading,Tags,icons} from './ui';
import {skillGroups,profile} from '@/content/profile';
export function SkillsGrid({compact=false}:{compact?:boolean}){return <div className="skills-grid">{skillGroups.slice(0,compact?3:undefined).map(g=>{const Icon=icons[g.icon as keyof typeof icons];return <article className="skill-card" key={g.title}><Icon size={24} strokeWidth={1.5}/><h3>{g.title}</h3><p>{g.description}</p><Tags items={g.skills}/></article>})}</div>}
export function CurrentlyBuilding(){return <section className="building-panel"><div className="building-title"><GitBranch size={24}/><div><span className="eyebrow">THE WORK CONTINUES</span><h2>Currently Building</h2></div></div><div className="building-grid"><div><span className="status-label">ACTIVE PROJECT</span><h3>AI Job Match Agent</h3><p>A public FastAPI project with structured analysis, input validation, deterministic demo mode and a documented test workflow.</p><Link href="/projects/ai-job-match-assistant/" className="text-link">Explore the project</Link></div><div><span className="status-label">LAB PROJECT</span><h3>Microsoft 365 User Lifecycle</h3><p>A PowerShell lab project for Entra ID onboarding and offboarding with the Microsoft Graph PowerShell SDK, -WhatIf previews and Pester tests. Not used in production.</p><Link href="/projects/m365-user-lifecycle/" className="text-link">Explore the project</Link></div><div><span className="status-label">CURRENTLY LEARNING</span><h3>Agents & retrieval</h3><p>Studying agentic workflows, RAG and embeddings. None of my published projects use them yet; new experiments will be shared when they’re ready.</p><Link href="/github/" className="text-link">Follow the development</Link></div></div></section>}
export function ContactCTA(){return <section className="contact-cta"><div><span className="eyebrow">LET’S BUILD SOMETHING USEFUL</span><h2>Real problems.<br/><span className="blue">Intelligent possibilities.</span></h2><p>Hiring for IT support, systems administration or AI and automation work?<br/>Let’s talk about the next challenge.</p></div><Link href="/contact/" className="button primary">Start a conversation</Link></section>}
export function ExperienceCard(){return <div className="experience-card"><div className="experience-icon"><Network size={28}/></div><div><span className="status-label">PROFESSIONAL FOUNDATION</span><h3>Enterprise ICT Support</h3><p>Supporting an environment of 2,200+ users across 20+ sites. Hands-on experience across Microsoft 365, identity, endpoints and workplace technology.</p><Tags items={['Microsoft 365','Entra ID','Intune','Windows Autopilot','PowerShell','Windows 11','Networking']}/></div><Link href="/experience/" className="text-link">View experience</Link></div>}
export function WebSeo(){return <div className="capability-duo"><article><Code2 size={29}/><span className="eyebrow">WEB DEVELOPMENT</span><h3>The interface between<br/>an idea and its users.</h3><p>From my personal projects: responsive websites, API-connected applications and simple interfaces for AI tools.</p><Tags items={['Next.js','React','TypeScript','Responsive design']}/><Link href="/web-development/" className="text-link">Explore web development</Link></article><article><Search size={29}/><span className="eyebrow">SEO & PERFORMANCE</span><h3>Built to work well.<br/>And to be found.</h3><p>SEO fundamentals from my personal web projects: meaningful page structure, search-friendly metadata, sitemaps and mobile usability.</p><Tags items={['Technical SEO','Schema markup','Sitemaps']}/><Link href="/seo/" className="text-link">Explore SEO fundamentals</Link></article></div>}
